version: '3.8'
services:

  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: share-it-postgres-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  server:
    build: ShareItServer
    image: server-image
    container_name: share-it-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  gateway:
    build: ShareItGateway
    image: gateway-image
    container_name: share-it-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090